---
# tasks file for terraform-ansible-install

  - name: Unarchive a file that needs to be downloaded
    include: terraform_install.yml
          
  - name: Install ansible on Debian or Ubuntu
    include: jessie_trusty.yml
    when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian' and ansible_distribution_release == 'trusty' or ansible_distribution_release == 'jessie' 
  
  - name: Install ansible on Debian or Ubuntu
    include: stretch_xenial.yml
    when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian' and ansible_distribution_release == 'xenial' or ansible_distribution_release == 'stretch'

  - name: Install ansible on Debian or Ubuntu
    include: buster_bionic.yml
    when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian' and ansible_distribution_release == 'bionic' or ansible_distribution_release == 'buster'

  - name: Install ansible on CentOS or Red Hat
    include: centos_redhat_7.yml
