---

##

  - name: Add specified repository into sources list
    apt_repository:
      repo: deb '{{ apt_repo }}' xenial main
      state: present

  - name: Add an apt key by id from key server
    apt_key:
      keyserver: '{{ key_server }}'
      id: '{{ key_id }}'

  - name: Update the repository cache and udpate package "ansible" to latest version using default release stretch or xenial
    apt:
      name: ansible
      state: present
      update_cache: yes
